<?php

namespace Application\Sonata\MediaBundle\Entity;

use Fort\Bundle\AdministrationBundle\Entity\Membre;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 * @ORM\Entity(repositoryClass="Application\Sonata\MediaBundle\Repository\MediaRepository")
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var Membre
     *
     * @ORM\OneToMany(targetEntity="Fort\Bundle\AdministrationBundle\Entity\Membre", cascade={"persist","remove"} ,mappedBy="photo", fetch="LAZY" )
     */
    protected $membres;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}
