fort_bundle_administration:
    resource: "@FortBundleAdministrationBundle/Controller/"
    type:     annotation
    prefix:   /administration

app:
    resource: '@AppBundle/Controller/'
    type: annotation
