fort_bundle_administration_membre:
    resource: "@FortBundleAdministrationBundle/Controller/MembreController.php"
    type:     annotation

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administration

fort_bundle_administration:
    resource: "@FortBundleAdministrationBundle/Controller/"
    type:     annotation
    prefix:   /administration

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
