<?php

namespace Application\Sonata\MediaBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFourFirst()
    {
        $qb = $this->createQueryBuilder('g')
            ->setMaxResults(4)
            ->orderBy('g.updatedAt', 'ASC')
            ->getQuery();

        return $qb->execute();
    }
}
