<?php

namespace Application\Sonata\MediaBundle\Entity;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
}
